spring:
  application:
    name: server-a


  datasource:
    url: jdbc:mariadb://localhost:3307/server-a
    username: root
    password: 4gkrsus1qks!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

grpc:
  client:
    serverb:  # gRPC 서버인 server-b와 통신하기 위한 설정
      address: 'static://localhost:50051'  # gRPC 서버 주소
      enable-keep-alive: true  # KeepAlive 활성화
      keep-alive-without-calls: true  # 비활성 연결에서도 KeepAlive를 유지
  server:
    port: 50052

server:
  port: 9999


secretKey: ${SECRET_KEY}