spring:
  application:
    name: server-a
  config:
    import: "optional:file:secret.env"


  datasource:
    url: jdbc:mariadb://localhost:${DATA_PORT}/${DATA_NAME}
    username: ${DATA_USER}
    password: ${DATA_PWD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

grpc:
  client:
    serverb:  # gRPC 서버인 server-b와 통신하기 위한 설정
      address: ${GRPC_ADDRESS}  # gRPC 서버 주소
      enable-keep-alive: true  # KeepAlive 활성화
      keep-alive-without-calls: true  # 비활성 연결에서도 KeepAlive를 유지
  server:
    port: ${GRPC_PORT}

server:
  port: ${SERVER_PORT}


secretKey: ${SECRET_KEY}