spring:
  application:
    name: server-b
  config:
    import: "optional:file:secret.env"

server:
  port: ${SERVER_PORT}

grpc:
  server:
    port: ${GRPC_PORT}  # gRPC 서버가 실행될 포트
    enable-keep-alive: true  # KeepAlive 활성화
    keep-alive-without-calls: true  # 비활성 연결에서도 KeepAlive 유지


secretKey: ${SECRET_KEY}